# Generated by Django 4.1.5 on 2023-05-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=150)),
                ("nom", models.CharField(max_length=150)),
                ("adresse", models.CharField(max_length=150)),
                ("telephone", models.CharField(max_length=150)),
                ("sexe", models.CharField(max_length=150)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
