# Generated by Django 4.1.5 on 2023-05-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0002_teacher_student_classe_student_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prenom", models.CharField(max_length=150)),
                ("nom", models.CharField(max_length=150)),
                ("adresse", models.CharField(max_length=150)),
                ("telephone", models.CharField(max_length=150)),
                ("sexe", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                ("date_creation", models.DateField()),
                ("date_expiration", models.DateField()),
                ("description", models.TextField()),
                (
                    "vendeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Main.vendeur"
                    ),
                ),
            ],
        ),
    ]
