# Generated by Django 4.1.5 on 2023-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0003_vendeur_produit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendeur",
            name="sexe",
            field=models.CharField(
                choices=[("Masculin", "M"), ("Feminin", "F")],
                default="Masculin",
                max_length=15,
            ),
        ),
    ]
