from django.shortcuts import render
from django.db.models import Q

from .models import *
from django.db.models import Subquery

# Create your views here.

#Partie Une
#######################################################################################
# def student_list(request):
    #requetes OR
    #ça
    #post=Student.objects.filter(prenom="prenom0") | Student.objects.filter(nom="nom2")
    #ou bien
    #post=Student.objects.filter(Q(prenom="prenom0") | Q(nom="nom2"))
# This code is defining a view function called `student_list` that retrieves all instances of the
# `Student` model using the `all()` method and assigns them to the variable `post`. It then prints the
# SQL query generated by this queryset using the `query` attribute. Finally, it creates a dictionary
# called `context` with the `post` queryset as a value and renders the `output.html` template with
# this context using the `render` function.
    # post=Student.objects.all()
    # print(post.query)

    # context={
    #     'post':post,
    # }

    # return render(request, 'output.html',context)


#Fin Partie une
##################################################################################################
#Debut partie deux


# def student_list(request):
    #requetes OR
    #ça   
    #post=Student.objects.filter(Q(prenom="prenom0") & Q(nom="nom2"))
    #ou bien
    # post= Student.objects.filter(classe=14) & Student.objects.filter(prenom="prenom1")

    # context={
    #     'post':post,
    # }


    # return render(request,"output.html",context)

#Fin Partie Deux
##################################################################################################
#Debut partie Trois



# def student_list(request):
    
    #=============================================================================
    #permet de voir les etudiants dont leurs nom commence par R ou leur age terminant par 4 avec OR
    #post=Student.objects.filter(Q(prenom__startswith='R') | Q(age__endswith=4))  
    #=============================================================================  



    # context={
    #     'post':post,
    # }


    # return render(request,"output.html",context)


def vendeur(request):
    #=============================================================================
    #permet de voir les vendeurs dont leurs prenom commence par O et leur nom commencent par T avec requeste &
    # vendeur= Vendeur.objects.filter(Q(prenom__startswith="O") &  Q(nom__startswith="T"))
    #============================================================================= 
    #Ici nous avons une requetes qui filtra apartir de l'id 5 jusqu'a la fin
    #vendeur= Vendeur.objects.filter(~Q(id__lt=3))
    #============================================================================= 
    #permet d'afficher tous les vendeurs dont le nom commencent par O et recuperer seulement leur nom et leur prenom
    #vendeur = Vendeur.objects.filter( prenom__startswith='O').only("prenom", "nom")
    #============================================================================= 
    vendeur = Vendeur.objects.all()
    Produit.objects.filter(vendeur_id__in=Subquery(vendeur.values('id')))
    vendeur={
        'vendeur':vendeur,
    }
    return render(request, "vendeur.html", vendeur)



